#error
Prompt Category:
Bug Fixing

Prompt:
Getting the following pylint error.
app/models/category.py:4:0: W0611: Unused Task imported from app.models.task (unused-import)

User Observation:
It fixed pylint error but raised another error.
Error message:
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper[Category(category)], expression 'Task' failed to locate a name ('Task'). If this is a class name, consider adding this relationship() to the <class 'app.models.category.Category'> class after both dependent classes have been defined.

Response ID:
8778d2d5-e42c-4cbb-a340-9b9d924c6bf0