#error
Prompt Category:
Bug Fixing

Prompt:
Getting the folllowing errors while trying to access /api/categories. Can you fix this.
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper[Category(category)], expression 'Task' failed to locate a name ('Task'). If this is a class name, consider adding this relationship() to the <class 'app.models.category.Category'> class after both dependent classes have been defined.

User Observation:
It's successfully fixed the error.

Response ID:
5b0de577-01c5-47d2-aa7e-5b1f6f460419